version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - staticfiles:/backend/staticfiles
    ports:
      - "8000:8000"
    working_dir: /backend/
    env_file:
      - setup_scripts/.env
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles

    env_file:
      - setup_scripts/.env
    depends_on:
      - backend
volumes:
  staticfiles: