version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    env_file: setup_scripts/.env
    expose:
      - "8000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/frontend
    working_dir: /frontend
    env_file: setup_scripts/.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
  database:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=${BUSME_USER}
      - POSTGRES_PASSWORD=${BUSME_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
