version: "3"

services:
  database:
    image: postgres:14.4-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    volumes:
      - staticfiles:/backend/staticfiles
    ports:
      - "8000:8000"
    working_dir: /backend/
    env_file:
      - .env
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles

    env_file:
      - .env
    depends_on:
      - backend
volumes:
  staticfiles: