version: "3"

services:
  backend:
    build: ./backend
    network_mode: "host"
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    env_file: .env
    command: sh entrypoint.sh
  frontend:
    image: node:13-alpine
    command: sh entrypoint.sh
    working_dir: /frontend
    env_file: .env
    volumes:
      - ./frontend/:/frontend
  nginx:
    image: nginx:latest
    network_mode: "host"
    ports:
      - "1337:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
  database:
    image: postgres:14.4-alpine
    network_mode: "host"
    environment:
      - POSTGRES_USER=${BUSME_USER}
      - POSTGRES_PASSWORD=${BUSME_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"